[package]
name = "lol-thing-api"
version = "0.1.0"
authors = ["RandySiren <sranmandeep1997@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
league-client-connector = "0.1.*"